# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-18 08:39
from __future__ import unicode_literals

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(storage=main.models.OverwriteStorage(), unique=True, upload_to=main.models.PathAndRename())),
            ],
        ),
    ]
